### PR TITLE
MQTT server URL option

### PR DESCRIPTION
**Pull request by digitalcraig**
I'm not using Hassio, but instead running individual Docker containers on my QNAP NAS and I had trouble connecting to my mosquitto container. I switched to specifying a URL in the options instead of building a URL in the mqtt.connect and added a few more entries to mqtt_connect_options to make it work.  

I didn't include these extra options in my commit because not running as a hassio addon means I don't need to use config.json. I just created my own options.json in the container config directory. If these additional options are of interest, I'll be happy to share.

Since the mqtt library supports several different protocols, the URL options allows for more variety in configurations. My goal is to make a secure connection to mosquitto using the same self-signed client certificate I use with my Owntracks clients. For now I set up a second, non-SSL listener in mosquitto.

### CODE REVIEW

**Comment by haruny** [comment]
Hi Craig!

Thank you for this. And thank you for your original work that inspired me to work on it.

You're right, probably MQTT URL is a better choice. However I would love to do this change in a bit graceful way. I want to make sure we're not somehow breaking the configs for the folks who already installed the addon and auto updating every release in hassio. Also, I don't want to take away from the simplicity of the config since addons are meant to be configurable by the non-techies. 
Is it possible to add mqtt_url as optional with a empty check? if mqtt_url is not empty, it uses otherwise it relies on mqtt_host and options. Also need to iterate the version number in the config file to have the changes propagated.
 
On the other hand I'd want to pull the docker-build file now.

if you don't have time to do it, I can do it later. Let me know.

**Review by haruny — APPROVED** [review]

**Review by haruny — APPROVED** [review]

**Review by haruny — CHANGES_REQUESTED** [review]
- version iterationin the config file is needed
- is it possible to make mqtt_url optional?

**Comment by digitalcraig** [comment]
> if you don't have time to do it, I can do it later. Let me know.

Yes, good idea. I can make those changes.

**Comment by digitalcraig** [comment]
Requested changes committed.

**Comment by haruny** [comment]
Looks great. I merged. I tested as well. All good.

**Pull request merged**
