### PR TITLE
Add multiplatform Docker Hub build

### PR DESCRIPTION
**Pull request by digitalcraig**
Add additional Dockerfiles to support auto build for multiple architectures on Docker Hub with the default Dockerfile being for the Hassio addon. Also reverts change which likely broke the the Hassio add-on by hardcoding the default build to amd64. The default has now been moved back to the docker-build.sh script for local Docker builds. No other code changes so new version number not required.

### CODE REVIEW

**Comment by haruny** [comment]
Could you resolve the conflicts first?

**Comment by haruny** [comment]
Build.sh looks all html to me. Is that normal?

**Comment by haruny** [comment]
Sorry Craig. It still has conflicts, it says.

**Comment by digitalcraig** [comment]
I did resolve the conflicts manually, but it still says my repo is 1 commit behind. I'll try again. I think I know what happened with build.sh.

**Comment by haruny** [comment]
It doesn’t let me auto merge. Still says there are conflicts.

**Comment by digitalcraig** [comment]
Ok, conflicts resolved and removed build.sh. It was used part of an experiment with cross-build and I used another method.

**Comment by haruny** [comment]
Done.

**Pull request merged**
